//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCsecondProject.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvcCalısmaEntities : DbContext
    {
        public mvcCalısmaEntities()
            : base("name=mvcCalısmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_Kategori> TBL_Kategori { get; set; }
        public virtual DbSet<TBL_Musteri> TBL_Musteri { get; set; }
        public virtual DbSet<TBL_Satıslar> TBL_Satıslar { get; set; }
        public virtual DbSet<TBL_Urunler> TBL_Urunler { get; set; }
    }
}
