//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCsecondProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_Urunler()
        {
            this.TBL_Satıslar = new HashSet<TBL_Satıslar>();
        }
    
        public int UrunID { get; set; }
        public string UrunAd { get; set; }
        public string Marka { get; set; }
        public Nullable<int> UrunKategoriler { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<int> Stok { get; set; }
    
        public virtual TBL_Kategori TBL_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Satıslar> TBL_Satıslar { get; set; }
    }
}
